### ISSUE TITLE
Nokia YANG model: cannot call add() on decimal number 0.0

### ISSUE THREAD

**Issue by TribuneX** [openconfig/ygot#361]
Hi,

I am trying to generate go bindings for the Nokia YANG model published here:
https://github.com/nokia/7x50_YangModels/tree/db3ffd43852235c9ec453625df3b8ca9ccf3c742

However, I get the following error during code generation: 

```
go run ../../generator/generator.go -path=/Users/myuser/7x50_YangModels/YANG -output_file=pkg/ocdemo/oc.go -package_name=ocdemo /Users/myuser/7x50_YangModels/YANG/nokia-conf.yang 
panic: cannot call add() on decimal number 0.0

goroutine 1 [running]:
github.com/openconfig/goyang/pkg/yang.Number.add(0x0, 0x0, 0x1, 0x1, 0x0, 0x1, 0x0)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/types_builtin.go:703 +0x15c
github.com/openconfig/goyang/pkg/yang.coalesce(0xc0040824e0, 0x2, 0x2, 0x0, 0x0, 0x1)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/types_builtin.go:848 +0x169
github.com/openconfig/goyang/pkg/yang.ParseRanges(0xc0004247f0, 0xd, 0x12, 0x1, 0x0, 0x0, 0xe)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/types_builtin.go:827 +0x354
github.com/openconfig/goyang/pkg/yang.(*Type).resolve(0xc001a16d20, 0xc004219380, 0xa, 0x1a4b720)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/types.go:278 +0x1c9e
github.com/openconfig/goyang/pkg/yang.ToEntry(0x1687700, 0xc001a13bc0, 0x0)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:529 +0x50c1
github.com/openconfig/goyang/pkg/yang.ToEntry(0x1687480, 0xc001a0b880, 0xc004219200)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:728 +0x1d6d
github.com/openconfig/goyang/pkg/yang.ToEntry(0x16877c0, 0xc0019fa960, 0xc0041b2a80)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:672 +0x27af
github.com/openconfig/goyang/pkg/yang.ToEntry(0x1687480, 0xc001a0b340, 0xc0041b2900)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:736 +0x1c70
github.com/openconfig/goyang/pkg/yang.ToEntry(0x16877c0, 0xc0019fa780, 0xc004192a80)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:672 +0x27af
github.com/openconfig/goyang/pkg/yang.ToEntry(0x16877c0, 0xc00000c1e0, 0xc000a93b00)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:736 +0x1c70
github.com/openconfig/goyang/pkg/yang.ToEntry(0x1687480, 0xc000410540, 0xc000a93980)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:736 +0x1c70
github.com/openconfig/goyang/pkg/yang.ToEntry(0x16875c0, 0xc0001382c0, 0xc000a93800)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:672 +0x27af
github.com/openconfig/goyang/pkg/yang.ToEntry(0x1687800, 0xc000022c80, 0xc000a93680)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:678 +0x25cb
github.com/openconfig/goyang/pkg/yang.ToEntry(0x1687800, 0xc00030a280, 0xc000a93500)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:719 +0x3d57
github.com/openconfig/goyang/pkg/yang.ToEntry(0x1687800, 0xc00030a000, 0xc000a93380)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:719 +0x3d57
github.com/openconfig/goyang/pkg/yang.(*Modules).Process(0xc0002564b0, 0x7ffeefbff80b, 0x3b, 0x0)
	/Users/myuser/go/src/github.com/openconfig/goyang/pkg/yang/modules.go:329 +0x1c3
github.com/openconfig/ygot/ygen.processModules(0xc0000200e0, 0x1, 0x1, 0xc000209fb0, 0x1, 0x1, 0x1560000, 0x1, 0xc000091620, 0xc000195410, ...)
	/Users/myuser/go/src/github.com/openconfig/ygot/ygen/codegen.go:720 +0x2b2
github.com/openconfig/ygot/ygen.mappedDefinitions(0xc0000200e0, 0x1, 0x1, 0xc000209fb0, 0x1, 0x1, 0xc00418fd18, 0x13, 0x87, 0x13d3197, ...)
	/Users/myuser/go/src/github.com/openconfig/ygot/ygen/codegen.go:776 +0x9c
github.com/openconfig/ygot/ygen.(*YANGCodeGenerator).GenerateGoCode(0xc00418fd18, 0xc0000200e0, 0x1, 0x1, 0xc000209fb0, 0x1, 0x1, 0x1, 0x1, 0x100dfc6, ...)
	/Users/myuser/go/src/github.com/openconfig/ygot/ygen/codegen.go:316 +0x93
main.main()
	/Users/myuser/decix/ygot/generator/generator.go:268 +0x596
exit status 2
```

Any suggestion on how to move forward with this? Thanks a lot!

**Comment by robshakir** [comment]
Hi!

It looks like we hadn't seen a module that used ranges on decimals in this way before (where coalescing the ranges was required) -- I added support in the upstream goyang directory - and you can see the PR here at github.com/openconfig/goyang/pulls/115.

Note that also you will need the `-ignore_circdeps` switch to be able to parse these Nokia models -- this is an explicit choice that Nokia made for the models, so we had to add support for these kind of circular imports into the goyang+ygot toolchain.

If you pull the branch in the goyang repo and then retry with the switch above specified this should generate (I checked against the 19.10 and 20.2 releases in the repo that you provided).

Cheers,
r.

**Comment by wenovus** [comment]
openconfig/goyang#115 addresses the specific error message. Please check whether it works now for your models, thanks.

**Comment by TribuneX** [comment]
Thanks a lot for this effort! I was now able to process the nokia YANG files.
