### ISSUE TITLE
Generating Go structure for submodule

### ISSUE THREAD

**Issue by egr3s** [openconfig/ygot#484]
Hi,

I'm getting SIGSEGV error when trying to generate Go code for submodule of [Nokia YANG model](https://github.com/nokia/7x50_YangModels/tree/master/latest_sros_20.7)  :
```
 go run ~/go/src/github.com/openconfig/ygot/generator/generator.go -path=nokia -output_file=test_svc.go -package_name=test_svc -ignore_circdeps nokia/nokia-conf-svc-vprn.yang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52dbe3]

goroutine 1 [running]:
github.com/openconfig/goyang/pkg/yang.ToEntry(0xa4d6a0, 0xc0001b6000, 0xc000082f00)
        /home/test/go/src/github.com/openconfig/goyang/pkg/yang/entry.go:757 +0x3ea3
github.com/openconfig/goyang/pkg/yang.(*Modules).Process(0xc0002b5f20, 0x7ffe230ba6cf, 0x1e, 0x0)
        /home/test/go/src/github.com/openconfig/goyang/pkg/yang/modules.go:335 +0x37f
github.com/openconfig/ygot/ygen.processModules(0xc000020230, 0x1, 0x1, 0xc00028d6f0, 0x1, 0x1, 0x200001, 0x1, 0x1, 0x7f9f18a1ce98, ...)
        /home/test/go/src/github.com/openconfig/ygot/ygen/codegen.go:800 +0x2c6
github.com/openconfig/ygot/ygen.mappedDefinitions(0xc000020230, 0x1, 0x1, 0xc00028d6f0, 0x1, 0x1, 0xc0005f9cb8, 0xc000305e40, 0x10, 0x10, ...)
        /home/test/go/src/github.com/openconfig/ygot/ygen/codegen.go:856 +0x9c
github.com/openconfig/ygot/ygen.(*YANGCodeGenerator).GenerateGoCode(0xc0005f9cb8, 0xc000020230, 0x1, 0x1, 0xc00028d6f0, 0x1, 0x1, 0x1, 0x1, 0x8, ...)
        /home/test/go/src/github.com/openconfig/ygot/ygen/codegen.go:390 +0x93
main.main()
        /home/test/go/src/github.com/openconfig/ygot/generator/generator.go:349 +0x5d5
exit status 2
```

Is it possible to generate a structure for submodule, or should I use top module instead? Generation for top module works fine.
go version go1.15.6 linux/amd64

**Comment by wenovus** [comment]
I think ygot/goyang treats each module as a unit view, so I think generating each submodule is not supported. Is a full generation of a module something you can work with?

**Comment by egr3s** [comment]
Sure, I can work with full module. Just wanted to clarify this. Thank you.
